### ISSUE TITLE
cannot access to aws s3, can you provide baiduyun file?

### ISSUE THREAD

**Issue by amberwangyili** [jshi31/T2ONet#1]
![3371627439851_ pic](https://user-images.githubusercontent.com/32975606/127254772-f8ccbbb4-193a-4898-be8e-9133dc14df26.jpg)

**Comment by amberwangyili** [comment]
![3381627440237_ pic](https://user-images.githubusercontent.com/32975606/127255322-0f590cc9-7022-4858-8071-9d90c9d2b0dc.jpg)

**Comment by zyhrainbow** [comment]
I meet the same problem, how do you solve it?

**Comment by jshi31** [comment]
Hi, having moved them to google drive
